---
# The plays for zookeper daemons

- name: rm conf dir file
  sudo: yes
  shell: rm /etc/zookeeper/conf/* -rf

- include: ../../conf/tasks/zookeeper.yml

- name: init zookeeper
  sudo: yes
  shell:  /sbin/service zookeeper-server init --myid={{zookeeper__zoo_id}} --force

