
- name: Create the data directory for the datanode dir
  sudo: yes
  file: path={{item}} owner=hdfs group=hdfs state=directory
  with_items: hdfs__dfs_datanode_data_dir

- name: register the dir
  shell: dirname {{ hdfs__dfs_domain_socket_path }}
  register: domain_socket_path

- name: mkdir short cut dir
  sudo: yes
  file: path={{ domain_socket_path.stdout }} owner=hdfs group=hdfs mode=755 state=directory
