---
# Playbook for  Hadoop master servers

- name: Install the namenode packages
  sudo: yes
  yum: name={{item}} state=installed
  with_items: 
   - hadoop-hdfs-namenode
   - hadoop-hdfs-zkfc
   - hadoop-lzo-cdh4
   - bigtop-utils

