---

- include: ../../conf/tasks/hive.yml

- name: use the new start sh for use java agent
  sudo: yes
  copy: src=hiveserver.sh dest=/usr/lib/hive/bin/ext/hiveserver.sh mode=0755

- name: start hive server
  sudo: yes
  script: start.sh



