
- hosts:
  - hadoop2
  tasks: 
  - include: roles/gmetad/tasks/stop.yml
  - include: roles/gmetad/tasks/stop_web.yml

- hosts:
  - hadoop4
  - hadoop2
  - hadoop5
  tasks:
  - include:  roles/gmond/tasks/stop.yml



#  - include: roles/gmond/tasks/conf.yml
