
- hosts: GMETAD
  tasks:
  - include: roles/gmetad/tasks/stop.yml

- hosts: GMOND
  tasks:
  - include:  roles/gmond/tasks/stop.yml


- hosts: GMETAD
  tasks:
  - include: roles/gmetad/tasks/start.yml

- hosts: GMOND
  tasks:
  - include:  roles/gmond/tasks/start.yml

