

- name: register jar var
  shell: ls {{HDFS_HOME}}|grep "hadoop-hdfs-2.0.0-cdh4.2.1-1009" |wc -l
  register: new_jar

- name: copy the hdfs's jar
  sudo: yes
  copy: src={{ JAR_DIR }}/{{item}} dest={{HDFS_HOME}}
  with_items:
    - hadoop-hdfs-2.0.0-cdh4.2.1-1009.jar
  when: new_jar.stdout|int == 0

- name: remove the old one
  sudo: yes
  shell: rm -f {{ HDFS_HOME }}/hadoop-hdfs-2.0.0-cdh4.2.1.jar ;
  when: new_jar.stdout|int == 0

- name: ln new one
  sudo: yes
  shell: cd {{ HDFS_HOME }} ; ln -sf hadoop-hdfs-2.0.0-cdh4.2.1-1009.jar hadoop-hdfs.jar
  when: new_jar.stdout|int == 0
