---

- name: mkdir temp
  file: path=/tmp/ansible/hive mode=777 state=directory

- name: copy file
  copy: src={{item}} dest=/tmp/ansible/hive/{{item}}
  with_items:
  - hive-schema-0.10.0.mysql.sql

- name: init hive database
  shell: cat /tmp/ansible/hive/{{item}} | mysql -h{{hive__mysql_host}} -P{{hive__mysql_port}} -u{{hive__mysql_user}} -p{{hive__mysql_passwd}} -D{{hive__mysql_database}}
  with_items:
  - hive-schema-0.10.0.mysql.sql
