
- include: ../../conf/tasks/hive.yml

- name: use the new start sh for use java agent
  sudo: yes
  copy: src=metastore.sh dest=/usr/lib/hive/bin/ext/metastore.sh mode=0755

- name: start hive metastore
  sudo: yes
  script: start.sh {{ hive__hive_metastore_port }}

#bug吗？ 不知道为什么不能启动
#- name: start hive metastore
#  sudo: yes
#  service: name=hive-metastore state=started
#  environment:
#    PORT: hive__hive_metastore_port


