---

- hosts: 
  - NAMENODE[0]
  tasks:
  - name: test ssh to other
    sudo_user: hdfs
    script: script/test_ssh.sh {{ ansible_ssh_port }} {{ groups.NAMENODE[1] }}

- hosts: 
  - NAMENODE[1]
  tasks:
  - name: test ssh to other
    sudo_user: hdfs
    script: script/test_ssh.sh {{ ansible_ssh_port }} {{ groups.NAMENODE[0] }}
