---

##初始化ZK

- hosts: ZOOKEEPER
  tasks:
  - include: roles/zookeeper/tasks/start.yml

- hosts:
  - NAMENODE[0]
  tasks:
  - name: format zk
    script: script/format.sh zk
    sudo: yes
    sudo_user: hdfs

##生成nn1,nn2hdfs的sshkey,并保证互通

- hosts: NAMENODE
  tasks:
  - name: run build hdfs ssh key 
    sudo: yes
    sudo_user: hdfs
    script: script/build_hdfs_ssh.sh

- hosts: 
  - NAMENODE[0]
  tasks:
  - name: test ssh to other
    sudo_user: hdfs
    script: script/test_ssh.sh {{ ansible_ssh_port }} {{ groups.NAMENODE[1] }}

- hosts: 
  - NAMENODE[1]
  tasks:
  - name: test ssh to other
    sudo_user: hdfs
    script: script/test_ssh.sh {{ ansible_ssh_port }} {{ groups.NAMENODE[0] }}
