---

- hosts: NODEMANAGER
  tasks:
  - include: roles/nodemanager/tasks/init.yml

- hosts:
  - NAMENODE[0]
  sudo: yes
  sudo_user: hdfs
  tasks:
  - name: init yarn user directory
    shell: hdfs dfs -mkdir -p {{item}} ; hdfs dfs -chown yarn:yarn {{item}}
    with_items:
     - /user/yarn

  - name: init done dir
    shell: hdfs dfs -mkdir {{item}} ; hdfs dfs -chmod 750 {{item}}
    with_items:
     -  "{{yarn__mapreduce_jobhistory_done_dir}}"

  - name: init  intermediate-done-dir dir
    shell: hdfs dfs -mkdir -p {{item}} ;  hdfs dfs -chmod 1777 {{item}}
    with_items:
     -  "{{yarn__mapreduce_jobhistory_intermediate_done_dir}}"

  - name: mkdir log dir
    shell: hdfs dfs -mkdir -p {{item}} ; hdfs dfs -chown yarn:mapred {{item}} ; hdfs dfs -chmod 1777 {{item}}
    with_items:
    - "{{yarn__yarn_nm_remote_app_log_dir}}"
