

- hosts: QJM
  tasks:
  - include: roles/qjm/tasks/stop.yml

- hosts: NAMENODE
  tasks:
  - include: roles/namenode/tasks/stop.yml

- hosts: DATANODE
  tasks:
  - include: roles/datanode/tasks/stop.yml


- hosts: QJM
  tasks:
  - include: roles/qjm/tasks/start.yml

- hosts: NAMENODE
  tasks:
  - include: roles/namenode/tasks/start.yml

- hosts: DATANODE
  tasks:
  - include: roles/datanode/tasks/start.yml

