



- hosts: IMPALASTATESTORE
  tasks:
  - include: roles/impalastatestore/tasks/stop.yml

- hosts: IMPALASERVER
  tasks:
  - include: roles/impalaserver/tasks/stop.yml



- hosts: IMPALASTATESTORE
  tasks:
  - include: roles/impalastatestore/tasks/start.yml

- hosts: IMPALASERVER
  tasks:
  - include: roles/impalaserver/tasks/start.yml


