
- hosts: SOLRSERVER
  tasks:
  - include: roles/solrserver/tasks/stop.yml

- hosts: HBASEINDEXER
  tasks:
  - include: roles/hbaseindexer/tasks/stop.yml

- hosts: SOLRSERVER
  tasks:
  - include: roles/solrserver/tasks/start.yml

- hosts: HBASEINDEXER
  tasks:
  - include: roles/hbaseindexer/tasks/start.yml
