
- hosts: RESOURCEMANAGER
  tasks:
  - include: roles/resourcemanager/tasks/setup.yml

- hosts: NODEMANAGER
  tasks:
  - include: roles/nodemanager/tasks/setup.yml

- hosts: HISTORYSERVER
  tasks:
  - include: roles/historyserver/tasks/setup.yml
