---

- name: template the gmond conf
  sudo: yes
  template: src=gmond.conf.j2 dest=/etc/ganglia/gmond.conf

- name: template the gmond python conf
  sudo: yes
  template: src=python.pyconf.j2 dest=/etc/ganglia/conf.d/{{item.name}}.pyconf
  with_items:
   - "{{ ganglia__gmond_python }}"

- name: copy the gmond python py
  sudo: yes
  copy: src={{item.name}}.py dest=/usr/lib64/ganglia/python_modules/{{item.name}}.py
  with_items:
   - "{{ ganglia__gmond_python }}" 
