---

- name: copy hbaseindexer conf
  sudo: yes
  template: src=hbaseindexer/{{item}}.j2 dest=/etc/hbase-solr/conf/{{item}}
  with_items:
    - hbase-indexer-site.xml
    - hbase-indexer-env.sh
    - log4j.properties  


- name: copy the hbase-site.xml to conf
  sudo: yes
  template: src=hbase/{{item}}.j2 dest=/etc/hbase-solr/conf/{{item}}
  with_items:
    - hbase-site.xml 
