
- name: copy hbase conf
  sudo: yes
  template: src={{ TEMPLATE_DIR }}/hbase/{{item}}.j2 dest=/etc/hbase/conf/{{item}}
  with_items:
    - hbase-site.xml
    - log4j.properties
    - hbase-env.sh
    - hbase-regionserver-jmxetric.xml
    - hbase-master-jmxetric.xml
    - hbase-jmxetric-logging.properties

#    - hadoop-metrics.properties
