
- name: copy hadoop conf
  sudo: yes
  template: src={{ TEMPLATE_DIR }}/hadoop/{{item}}.j2 dest=/etc/hadoop/conf/{{item}}
  with_items:
    - core-site.xml
    - hdfs-site.xml
    - hdfs-site.private.xml
    - log4j.properties
    - hadoop-env.sh
    - hadoop-metrics2.properties
    
