
- name: copy hive conf
  sudo: yes
  template: src=hive/{{item}}.j2 dest=/etc/hive/conf/{{item}}
  with_items:
    - hive-site.xml
    - hive-env.sh
    - hive-log4j.properties
    - hive-exec-log4j.properties
    - hive-metastore-jmxetric.xml
    - hive-server-jmxetric.xml
    - hive-server2-jmxetric.xml
