
- name: copy httpfs conf
  sudo: yes
  template: src=hadoop/{{item}}.j2 dest=/etc/hadoop-httpfs/conf/{{item}}
  with_items:
    - httpfs-site.xml
    - httpfs-signature.secret
    - httpfs-log4j.properties
    - httpfs-env.sh 
