
- include: hdfs.yml

- name: copy hadoop conf
  sudo: yes
  template: src={{ TEMPLATE_DIR }}/hadoop/{{item}}.j2 dest=/etc/hadoop/conf/{{item}}
  with_items:
    - mapred-site.xml
    - yarn-site.xml
    - yarn-site.private.xml
    - yarn-env.sh
    
